### ISSUE TITLE
system:index property is hidden when displaying featureCollection

### ISSUE THREAD

**Issue by 12rambau** [aazuspan/eerepr#42] opened 2024-12-05 01:58 UTC
I am using eerpr as much as I can (i.e. whenever I'm playing in a notebook) and I recently fell on a small trap. I was displaying a test dataset: 

```python 
## Import the example feature collection and drop the data property.
ecoregions = (
    ee.FeatureCollection("projects/google/charts_feature_example")
    .select(["label", "value", "warm"])
)
ecoregions
```

and when looking at the result I saw 3 properties per `Feature` object: 
![image](https://github.com/user-attachments/assets/3eecb91b-5876-4064-b340-be2e0dc3825f)

But in reality when I manually look into it: 
```python 
ecoregions.first.propertyNames()
```
![image](https://github.com/user-attachments/assets/9cc68362-0ee6-4548-a323-68f2cf3dff61)

Is it intentional to hide the `systemm:index` property in the display ? 

PS: I tested it with other dataset (FAO GAUL and WWF hydroshed) and the behaviour is the same.

**Comment by aazuspan** [comment] 2024-12-05 05:35
Hi @12rambau, I hadn't noticed this before, but it looks like it is consistent with the Code Editor (which is the goal of eerepr). Here's the same feature and property names there:

![image](https://github.com/user-attachments/assets/96932f74-edad-4d5f-8d8e-61634d0fde7c)

The root cause seems to be that the JSON returned by `ee.Feature.getInfo` (below) includes the `system:index` as a feature-level `id` rather than as a `system:index` in the properties. 

```python
{'type': 'Feature',
 'geometry': {'type': 'Polygon',
  'coordinates': [[[-109.20999998777032, 31.420000027612016],
    [-108.3000000221122, 31.41999998395071],
    [-108.3000000221122, 32.029999957333146],
    [-109.20999998777032, 32.03000002411591],
    [-109.20999998777032, 31.420000027612016]]]},
 'id': '00000000000000000000',
 'properties': {'label': 'Desert', 'value': 0, 'warm': 1}}
```

Interestingly, this only seems to affect `ee.Feature`. Images and feature collections both return a `system:index` property. Not sure if that was an intentional choice or a bug, but it's definitely on the GEE side.

Thanks for reporting though, and glad to hear you're finding eerepr useful!

**Comment by 12rambau** [comment] 2024-12-05 14:08
I made few small experiments and indeed everything that is prefixed by `system:` is not displayed without checking if it's user created or a real system one. My guess is that they actually implemented https://issuetracker.google.com/issues/329235200 only in the user interface.

**Comment by aazuspan** [comment] 2024-12-06 01:54
Interesting, thanks for digging in. I'm closing for now since we're consistent with the Code Editor, but feel free to re-open if there are changes that require work in eerepr.

**Closed** 2024-12-06 01:54 UTC
